zn.define([
    './ChunRuiOAUser',
    './ChunRuiOAExpressCompany',
    './ChunRuiOACustomer',
    './ChunRuiOACustomerInvoice',
    './ChunRuiOACustomerInvoiceDetail',
    './ChunRuiOACustomerProductQuote',
    './ChunRuiOASupplier',
    './ChunRuiOASupplierProductQuote',
    './ChunRuiOASupplierServiceBack',
    './ChunRuiOACustomerBill'
]);
