zn.define([
    './Bill',
    './In',
    './Init',
    './Invoice',
    './Customer',
    './Express',
    './Quote',
    './Sale',
    './Service',
    './Stock',
    './Supplier',
    './SupplierService',
    './User',
    './CustomerBill'
]);
